# Generated by Django 3.0.1 on 2020-08-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userresponse1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Policyname', models.CharField(max_length=20)),
                ('Question1', models.CharField(max_length=30)),
                ('Question2', models.CharField(max_length=30)),
                ('Question3', models.CharField(max_length=30)),
                ('Question4', models.CharField(max_length=30)),
                ('Question5', models.CharField(max_length=30)),
            ],
        ),
    ]
